EncryptionHelper TryDecryptAES256 throws exception
grandchamp/Identity.Dapper pull request #66
Opened 2018-01-31 23:16 UTC by terzano

When trying to decrypt a string, the method throws the following exception "The input data is not a complete block." and returns the same input given (tested under .NET Core 2.0).
I noticed this when my logs where being flooded with errors on User registration. 

Log Entry Example:
`{"Level": "Error", "Timestamp": "2018-01-23T12:13:22.6762643+00:00", "Properties": {"ActionId": "28bbddb1-ff40-4880-af22-2a7ef7e6dabc", "ThreadId": 9, "RequestId": "0HLB1K4845IA8:00000001", "ActionName": "Fmp.Web.Controllers.API.AccountController.Register (Fmp.Web)", "Application": "FMP", "MachineName": "RD00155D8A52DB", "ProcessName": "dotnet", "RequestPath": "/api/v1.0/account/register", "SourceContext": "Identity.Dapper.Cryptography.EncryptionHelper"}, "MessageTemplate": "Specified padding mode is not valid for this algorithm."}`

I added a Test so you can see the behavior and a possible Fix using the same AES256 Algorithm.
Also, notice that I am not doing Base64 on the Key/IV. You are welcome to revert this.

2018-02-06 17:43 UTC, grandchamp commented
@terzano sorry for the late.
I had no time to analyse your pull request.

The current method by design return the same input on exception because if you don't encrypt it'll throw exception. What i could do is remove the log of the exception and you'll no longer be flooded by these exceptions.

2018-02-07 18:20 UTC, terzano commented
@grandchamp The issue is not what happens when the exceptions is thrown (I left that part the same). The problem is that the Decryption method is not working, it always throws an exception.

2018-02-07 18:30 UTC, grandchamp commented
I thought i had some tests for it.
I'll check it out.

2018-02-07 18:59 UTC, grandchamp commented
@terzano i've added a simple review to your commit.
Anyway, can you update the repo README and the sample to consider your changes?

2018-02-07 19:01 UTC, grandchamp requested changes

2018-02-07 19:01 UTC, grandchamp commented on src/Identity.Dapper/Cryptography/EncryptionHelper.cs
> +            var iv = System.Text.Encoding.ASCII.GetBytes(_aesKeys.Value.IV);
Can you make this line UTF8 too?

2018-02-07 19:07 UTC, grandchamp requested changes

2018-02-07 19:07 UTC, grandchamp commented on src/Identity.Dapper/Cryptography/EncryptionHelper.cs
> +            var iv = System.Text.Encoding.ASCII.GetBytes(_aesKeys.Value.IV);
After you change the other line, this will change to UTF8 too.

2018-02-07 20:41 UTC, terzano commented
@grandchamp I modified the vector encoding as suggested. 
Keep in mind that there is a breaking change. The Key & IV are not Base64 encoded. I can restore that by adding to maintain full compatibility. 
```
Convert.FromBase64String(_aesKeys.Value.Key) 
Convert.FromBase64String(_aesKeys.Value.IV)
```

2018-02-08 10:59 UTC, grandchamp commented
Well... I don't see any problems on your implementation with a hex and plain text.
It's your choice, but if we maintain yours, i'll ask you to update the README and the sample, as i mentioned before.

2018-02-08 17:01 UTC, terzano commented
That sounds reasonable. I will try to find some time to make the update today.

2018-02-09 00:16 UTC, terzano commented
Decided to maintain backwards compatibility, less friction for your user base. Made the proper changes and updated the docs and test project as suggested.

2018-02-09 10:59 UTC, grandchamp approved these changes

2018-02-09 11:00 UTC, grandchamp commented
Very good job!
Thanks!

2018-02-09 11:00 UTC, merged